import {useCallback,useEffect,useRef,useState} from 'react';
import {HubConnectionBuilder,LogLevel} from '@microsoft/signalr';
import {Activity,ArrowUpRight,AudioLines,BookOpen,Calendar,Camera,Check,ChevronRight,Compass,Globe,Home,Layers,LogOut,Mail,Menu,MessageSquare,Mic,Monitor,Phone,Search,Send,Settings as SettingsIcon,Shield,Square,Terminal,Users,X} from 'lucide-react';
import {api,Doc,errorText,setCsrf} from './api';
import Auth from './Auth';import Settings from './Settings';import Voice from './Voice';import {Approvals,DataPanel,Permissions,ToolPanel} from './Panels';
import {TaskBoard,PersonalMemoryPanel,ModelDashboard,SipStatus} from './OperatorPanels';
import LocalNetwork from './LocalNetwork';
const nav=[['Home',Home],['Chat',MessageSquare],['Voice',AudioLines],['Research',Compass],['Browser',Globe],['Devices',Monitor],['Local Network',Shield],['Tasks & Goals',Layers],['Nextcloud',BookOpen],['Immich',Camera],['Calendar',Calendar],['Mail',Mail],['Phone',Phone],['Calls',Phone],['Memory',BookOpen],['Obsidian',Layers],['Automations',Activity],['Contacts',Users],['AI Models',Terminal],['Freigaben',Check],['Permissions',Shield],['Audit Log',Activity],['Events',Activity],['System',Layers],['Settings',SettingsIcon]] as const;
function safeUrl(url:string){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
export default function App(){
 const[ready,setReady]=useState(false),[setup,setSetup]=useState(false),[user,setUser]=useState<any>(),[page,setPage]=useState('Home'),[error,setError]=useState(''),[menu,setMenu]=useState(false);
 const[devices,setDevices]=useState<Doc[]>([]),[audit,setAudit]=useState<any[]>([]),[tasks,setTasks]=useState<Doc[]>([]),[events,setEvents]=useState<string[]>([]),[health,setHealth]=useState(false);
 const refresh=useCallback(async()=>{try{const[d,a,t]=await Promise.all([api<Doc[]>('/devices'),api<any[]>('/audit'),api<Doc[]>('/data/tasks')]);setDevices(d);setAudit(a);setTasks(t)}catch(e){setError(errorText(e))}},[]);
 const init=useCallback(async()=>{try{const status=await api('/setup/status');setSetup(status.required);if(!status.required){try{const me=await api('/auth/me');setUser(me.user);setCsrf(me.csrf)}catch{setUser(null)}}}catch(e){setError(errorText(e))}finally{setReady(true)}},[]);
 useEffect(()=>{init()},[init]);
 useEffect(()=>{if(!user)return;refresh();fetch('/health/ready').then(r=>setHealth(r.ok)).catch(()=>setHealth(false));
  const hub=new HubConnectionBuilder().withUrl('/hubs/events').withAutomaticReconnect().configureLogging(LogLevel.Error).build();
  ['research','tool','job','device','call','automation','notification','task','event','activity'].forEach(topic=>hub.on(topic,e=>{setEvents(prev=>[e.message||[e.tool,e.status].filter(Boolean).join(' ')||topic,...prev].slice(0,12))}));
  hub.on('notification',e=>{if('Notification' in window&&Notification.permission==='granted')new Notification(e.title,{body:e.message})});
  hub.start().catch(()=>setEvents(['Live-Verbindung unterbrochen. Manuelles Aktualisieren ist verfügbar.']));
  const timer=setInterval(refresh,30000);const renew=setInterval(()=>api('/auth/refresh','POST',{}).then(r=>setCsrf(r.csrf)).catch(()=>setUser(null)),30*60*1000);
  return()=>{hub.stop();clearInterval(timer);clearInterval(renew)}
 },[user,refresh]);
 if(!ready)return <div className="loading">JARVIS wird verbunden …</div>;
 if(!user)return <>{error&&<p className="error">{error}</p>}<Auth setup={setup} onDone={init}/></>;
 const online=devices.filter(d=>!d.data.revoked&&Date.now()-Date.parse(d.data.lastSeen)<90000).length;
 return <div className="shell"><aside className={'sidebar '+(menu?'shown':'')}><div className="brand"><span className="brandmark">J</span>JARVIS</div><p className="eyebrow">PERSONAL INTELLIGENCE</p><nav>{nav.map(([label,Icon])=><button key={label} className={page===label?'active':''} onClick={()=>{setPage(label);setMenu(false)}}><Icon size={18}/><span>{label}</span>{label===page&&<ChevronRight size={14}/>}</button>)}</nav><div className="profile"><span className="avatar">{user.username?.slice(0,1).toUpperCase()}</span><div><strong>{user.username}</strong><small>Persönlicher Workspace</small></div><button aria-label="Abmelden" onClick={async()=>{await api('/auth/logout','POST',{});setUser(null)}}><LogOut size={16}/></button></div></aside>
 <div className="workspace"><header className="topbar"><div className="row"><button className="mobilemenu" onClick={()=>setMenu(!menu)} aria-label="Menü"><Menu/></button><span className="muted">Workspace</span><ChevronRight size={13}/><strong>{page}</strong></div><div className="row"><span className={'statusdot '+(health?'online':'')}/><small>{health?'System erreichbar':'Status wird geprüft'}</small><span className="badge">PRIVATE</span></div></header>
 <main><div className="pagehead"><div><p className="eyebrow">{new Intl.DateTimeFormat('de',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</p><h1>{page==='Home'?'Hallo, '+user.username+'.':page}</h1><p className="muted">{page==='Home'?'Was möchtest du heute erledigen?':'Dein Assistent, unter deiner Kontrolle.'}</p></div><button onClick={refresh}><Activity size={16}/>Aktualisieren</button></div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Fehler schließen"><X size={16}/></button></div>}
 {page==='Home'&&<><div className="hero"><div><span className="badge">JARVIS WORKSPACE</span><h2>Eine Frage.<br/>Viele Möglichkeiten.</h2><p>Recherchieren, organisieren, erinnern.<br/>Deine Werkzeuge arbeiten zusammen.</p><button className="lightbutton" onClick={()=>setPage('Chat')}>Gespräch beginnen<ArrowUpRight size={18}/></button></div><div className="heroart"><div className="ring ring1"/><div className="ring ring2"/><div className="core"><AudioLines size={64}/></div><span className="artlabel">CONNECTED TO YOUR WORLD</span></div></div>
 <div className="metrics"><Metric label="Geräte online" value={online+'/'+devices.length} text="Freigegebene Geräte" icon={<Monitor/>}/><Metric label="Offene Aufgaben" value={tasks.filter(t=>t.data.status!=='completed').length} text="In deinem Workspace" icon={<Layers/>}/><Metric label="Letzte Aktionen" value={audit.length} text="Gespeicherte Audit-Einträge" icon={<Shield/>}/></div>
 <div className="twocol"><section className="panel"><div className="sectionhead"><h2>Deine Geräte</h2><button onClick={()=>setPage('Devices')}>Verwalten<ArrowUpRight size={16}/></button></div>{devices.length?devices.map(d=><div className="deviceitem" key={d.id}><Monitor/><div><strong>{d.data.name}</strong><small>{d.data.platform} · {d.data.resolution||'Auflösung unbekannt'}</small></div><span className="badge">{!d.data.revoked&&Date.now()-Date.parse(d.data.lastSeen)<90000?'Online':'Offline'}</span></div>):<div className="empty">Verbinde deinen ersten Computer oder dein iPhone.<button onClick={()=>setPage('Devices')}>Gerät hinzufügen</button></div>}</section><section className="panel"><h2>Zuletzt passiert</h2>{audit.slice(0,5).map(a=><div className="timelineitem" key={a.id}><span className="statusdot online"/><div><strong>{a.tool}</strong><small>{a.status} · {new Date(a.created_at).toLocaleTimeString()}</small></div></div>)}{audit.length===0&&<div className="empty">Aktionen erscheinen hier, sobald du JARVIS verwendest.</div>}</section></div>
 <div className="quicklinks">{[['Research','Quellen finden',Compass],['Voice','Lass uns sprechen',Mic],['Memory','Wissen festhalten',BookOpen]].map(([target,label,Icon]:any)=><button key={target} onClick={()=>setPage(target)}><Icon/><strong>{label}</strong><ArrowUpRight size={16}/></button>)}</div></>}
 {page==='Chat'&&<Chat/>}{page==='Voice'&&<Voice/>}{page==='Research'&&<><Research events={events}/><DataPanel kind="research" title="Gesamter Rechercheverlauf"/></>}
 {page==='Browser'&&<><p className="notice">Öffne einen Tab, nutze dessen ID für weitere Aktionen und fordere einen Screenshot an. Klicks und Formulare benötigen eine Freigabe.</p><ToolPanel prefix="Web."/><ToolPanel prefix="Browser."/></>}
 {page==='Devices'&&<Devices devices={devices} refresh={refresh}/>}
 {page==='Local Network'&&<LocalNetwork/>}
 {page==='Calendar'&&<ToolPanel prefix="Calendar."/>}{page==='Mail'&&<ToolPanel prefix="Mail."/>}{page==='Phone'&&<><SipStatus/><ToolPanel prefix="Phone."/></>}
 {page==='Calls'&&<DataPanel kind="calls" title="Gespräche & Ergebnisse"/>}
 {page==='Memory'&&<><PersonalMemoryPanel/><ToolPanel prefix="Memory."/><DataPanel kind="memory" title="Legacy-Erinnerungen (nicht verschlüsselt; manuell übernehmen)"/></>}
 {page==='Obsidian'&&<><ToolPanel prefix="File."/><Settings initial="obsidian"/></>}
 {page==='Automations'&&<DataPanel kind="automations" title="Automationen"/>}{page==='Contacts'&&<DataPanel kind="contacts" title="Kontakte"/>}
 {page==='Freigaben'&&<Approvals onChange={refresh}/>} {page==='Permissions'&&<Permissions/>}
 {page==='Audit Log'&&<section className="panel"><h2>Audit Log</h2><div className="tablewrap"><table><thead><tr><th>Zeit</th><th>Tool</th><th>Ergebnis</th><th>Dauer</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{new Date(a.created_at).toLocaleString()}</td><td>{a.tool}</td><td>{a.status}</td><td>{a.duration_ms} ms</td></tr>)}</tbody></table></div></section>}
 {page==='Settings'&&<Settings initial="ai"/>}{page==='AI Models'&&<><ModelDashboard/><Settings initial="ai"/></>}
 {page==='System'&&<><section className="panel"><h2>Systemzustand</h2><BrowserNotifications/><p>API, PostgreSQL, Redis und Migration: {health?'erreichbar / erfolgreich':'noch nicht bestätigt'}</p><p className="muted">Detaillierte Containerprüfungen: scripts/verify-installation.ps1 oder scripts/verify-installation.sh auf deinem Server.</p><a href="/openapi/v1.json" target="_blank" rel="noreferrer">OpenAPI-Spezifikation öffnen</a></section><DataPanel kind="tasks" title="Aufgaben"/></>}
 {page==='Tasks & Goals'&&<TaskBoard/>}{page==='Nextcloud'&&<ToolPanel prefix="Nextcloud."/>}{page==='Immich'&&<ToolPanel prefix="Immich."/>}{page==='Events'&&<><DataPanel kind="events" title="Ereignisse"/><DataPanel kind="event-rules" title="Ereignisregeln"/></>}
 </main><footer>JARVIS <span>Self-hosted personal intelligence</span><span>Keine Telemetrie.</span></footer></div></div>
}
function Metric({label,value,text,icon}:{label:string;value:string|number;text:string;icon:React.ReactNode}){return <section className="metric"><div>{icon}<span>{label}</span></div><strong>{value}</strong><small>{text}</small></section>}
function Chat(){
 const[input,setInput]=useState(''),[messages,setMessages]=useState<{role:string;text:string;sources?:any[]}[]>([]),[busy,setBusy]=useState(false),[image,setImage]=useState<string>(),[error,setError]=useState('');
 const conversation=useRef<string>(crypto.randomUUID()),abort=useRef<AbortController|null>(null);
 const[history,setHistory]=useState<Doc[]>([]);
 useEffect(()=>{api<Doc[]>('/data/chats').then(setHistory).catch(e=>setError(errorText(e)))},[]);
 async function send(e:React.FormEvent){e.preventDefault();if(!input.trim())return;const message=input;setInput('');setBusy(true);setError('');setMessages(m=>[...m,{role:'user',text:message}]);const controller=new AbortController();abort.current=controller;try{const r=await api('/chat','POST',{message,conversation:conversation.current,image},controller.signal);setMessages(m=>[...m,{role:'assistant',text:r.answer,sources:r.research?.sources}]);setImage(undefined);api<Doc[]>('/data/chats').then(setHistory).catch(()=>{})}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function capture(kind:'camera'|'screen'){try{const s=kind==='camera'?await navigator.mediaDevices.getUserMedia({video:true}):await navigator.mediaDevices.getDisplayMedia({video:true});try{const v=document.createElement('video');v.srcObject=s;await v.play();await new Promise(r=>setTimeout(r,250));const c=document.createElement('canvas');c.width=Math.min(v.videoWidth,1600);c.height=v.videoHeight*c.width/v.videoWidth;c.getContext('2d')!.drawImage(v,0,0,c.width,c.height);setImage(c.toDataURL('image/jpeg',0.8))}finally{s.getTracks().forEach(t=>t.stop())}}catch(e){setError(errorText(e))}}
 return <section className="panel chat"><div className="composer row"><select aria-label="Gesprächsverlauf" disabled={busy} value={conversation.current} onChange={e=>{conversation.current=e.target.value;setMessages((history.find(h=>h.id===e.target.value)?.data.messages||[]).map((m:any)=>({role:m.role,text:m.content,sources:m.sources})))}}><option value={conversation.current}>Aktuelles Gespräch</option>{history.filter(h=>h.id!==conversation.current).map(h=><option key={h.id} value={h.id}>{h.data.messages?.[0]?.content?.slice(0,65)||h.id}</option>)}</select><button disabled={busy} onClick={()=>{conversation.current=crypto.randomUUID();setMessages([])}}>Neues Gespräch</button></div><div className="chatbody">{messages.length===0&&<div className="chatwelcome"><span className="brandmark">J</span><h2>Wie kann ich dir helfen?</h2><p className="muted">Frage nach deinem Kalender, recherchiere ein Thema oder zeige mir einen freigegebenen Bildschirm.</p></div>}{messages.map((m,i)=><article className={'bubble '+m.role} key={i}><small>{m.role==='user'?'DU':'JARVIS'}</small><p>{m.text}</p>{m.sources&&<div className="sources">{m.sources.map(s=><a key={s.number} href={safeUrl(s.url)} target="_blank" rel="noreferrer">[{s.number}] {s.title}<ArrowUpRight size={14}/></a>)}</div>}</article>)}{busy&&<p className="working">JARVIS arbeitet …</p>}</div>{error&&<p className="error">{error}</p>}{image&&<div className="attachment"><img src={image} alt="Freigegebenes Einzelbild"/><button onClick={()=>setImage(undefined)}>Entfernen</button></div>}<form className="composer" onSubmit={send}><textarea aria-label="Nachricht" rows={2} placeholder="Frag JARVIS …" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(!busy)send(e)}}}/><div className="sectionhead"><div className="row"><button type="button" onClick={()=>capture('screen')} title="Bildschirm einmalig aufnehmen"><Monitor size={18}/></button><button type="button" onClick={()=>capture('camera')} title="Kamerabild einmalig aufnehmen"><Camera size={18}/></button><small>Bild wird erst beim Senden übertragen.</small></div>{busy?<button type="button" onClick={()=>abort.current?.abort()}><Square size={16}/>Stop</button>:<button className="primary" disabled={!input.trim()}><Send size={16}/>Senden</button>}</div></form></section>
}
function Research({events}:{events:string[]}){
 const[query,setQuery]=useState(''),[mode,setMode]=useState('research'),[fresh,setFresh]=useState(false),[jobs,setJobs]=useState<Doc[]>([]),[error,setError]=useState('');
 const load=()=>api<Doc[]>('/research').then(setJobs).catch(e=>setError(errorText(e)));
 useEffect(()=>{load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 async function start(e:React.FormEvent){e.preventDefault();try{await api('/research','POST',{question:query,mode,fresh});setQuery('');load()}catch(e){setError(errorText(e))}}
 return <><section className="panel"><p className="eyebrow">VON DER FRAGE ZUR QUELLE</p><h2>Wissen, das du nachprüfen kannst.</h2><form onSubmit={start}><textarea required minLength={3} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Was möchtest du herausfinden?" rows={3}/><div className="sectionhead"><div className="row"><select value={mode} onChange={e=>setMode(e.target.value)}><option value="quick">Quick Search · 1–3 Quellen</option><option value="research">Research</option><option value="deep">Deep Research</option></select><label className="check"><input type="checkbox" checked={fresh} onChange={e=>setFresh(e.target.checked)}/>Frisch recherchieren</label></div><button className="primary"><Search size={16}/>Recherche starten</button></div></form>{error&&<p className="error">{error}</p>}</section>
 {events.length>0&&<section className="panel compact"><h3>Aktivität</h3>{events.slice(0,4).map((e,i)=><p className="muted" key={i}>• {e}</p>)}</section>}
 {jobs.map(job=><section className="panel" key={job.id}><div className="sectionhead"><h2>{job.data.question}</h2><span className="badge">{job.data.status}</span></div>{['running','pending'].includes(job.data.status)&&<button onClick={()=>api('/research/'+job.id+'/cancel','POST',{}).then(load).catch(e=>setError(errorText(e)))}>Stoppen</button>}{job.data.error&&<p className="error">{job.data.error}</p>}{job.data.result&&<><p className="prose">{job.data.result.summary}</p><div className="sources">{job.data.result.sources?.map((s:any)=><a key={s.number} href={safeUrl(s.url)} target="_blank" rel="noreferrer"><span>[{s.number}]</span><div><strong>{s.title}</strong><small>{s.domain} · abgerufen {new Date(s.retrieved_at).toLocaleString()}</small></div><ArrowUpRight size={16}/></a>)}</div></>}</section>)}</>
}
function Devices({devices,refresh}:{devices:Doc[];refresh:()=>void}){
 const[pair,setPair]=useState<any>(),[error,setError]=useState('');
 return <><section className="panel"><div className="sectionhead"><h2>Verbundene Geräte</h2><button className="primary" onClick={()=>api('/devices/pairing','POST',{}).then(setPair).catch(e=>setError(errorText(e)))}>Gerät hinzufügen</button></div><p className="muted">Native Agenten verbinden sich ausgehend über HTTPS. Bildschirmzugriff und erlaubte Apps werden zusätzlich am Gerät freigegeben.</p>{error&&<p className="error">{error}</p>}{pair&&<div className="approval"><h3>Pairing-Code: {pair.code}</h3><p>Zusätzliches Pairing-Token (einmalig in den Agenten eingeben):</p><code className="secret">{pair.token}</code><small>Gültig bis {new Date(pair.expiresAt).toLocaleTimeString()}</small><button onClick={()=>setPair(null)}>Ausblenden</button></div>}{devices.map(d=><article className="record" key={d.id}><div className="sectionhead"><h3>{d.data.name}</h3><button className="danger" onClick={async()=>{if(confirm('Gerät widerrufen?')){await api('/devices/'+d.id+'/revoke','POST',{});refresh()}}}>Widerrufen</button></div><code>{d.id}</code><p>{d.data.platform} · {d.data.resolution} · Letzter Kontakt: {new Date(d.data.lastSeen).toLocaleString()}</p>{d.data.location&&<p>Standort: {d.data.location.latitude}, {d.data.location.longitude} (letzte Meldung)</p>}</article>)}</section><ToolPanel prefix="Device." onChange={refresh}/></>
}
function BrowserNotifications(){
 const[permission,setPermission]=useState('Notification' in window?Notification.permission:'unavailable');
 return <div className="record"><h3>Browser-Benachrichtigungen</h3><p className="muted">Nur bei geöffnetem Dashboard. Keine Hintergrund-Push-Nachrichten.</p><button disabled={permission!=='default'} onClick={()=>Notification.requestPermission().then(setPermission)}>Benachrichtigungen erlauben</button><small>{permission==='granted'?'Erlaubt':permission==='denied'?'In den Browsereinstellungen blockiert':permission==='unavailable'?'In diesem Browser nicht verfügbar':'Noch nicht erlaubt'}</small></div>
}
