import {useEffect,useRef,useState} from 'react';
import {api,errorText} from './api';
import {ToolPanel} from './Panels';

const blank=()=>({name:'',revision:'',host:'',protocol:'https',port:443,type:'HTTP',enabled:false,autoCheck:false,permission:'Read',credentialRef:'',allowHttpCredentials:false,readPaths:[] as string[]});
export default function LocalNetwork(){
 const[cfg,setCfg]=useState<any>({enabled:false,allowlist:[],ports:[80,443]}),[policy,setPolicy]=useState<any>(),[services,setServices]=useState<any[]>([]),[files,setFiles]=useState<any[]>([]),[entry,setEntry]=useState(''),[ports,setPorts]=useState('80,443'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const[service,setService]=useState(blank()),[id,setId]=useState(''),[paths,setPaths]=useState(''),[secret,setSecret]=useState({id:'',type:'Bearer',value:'',username:'',header:'X-Api-Key'}),[message,setMessage]=useState(''),[answer,setAnswer]=useState('');
 const conversation=useRef(crypto.randomUUID()),abort=useRef<AbortController|null>(null);
 const load=()=>Promise.all([api<any[]>('/local-network/services'),api<any[]>('/local-network/files')]).then(([s,f])=>{setServices(s);setFiles(f.map(x=>({...x,info:JSON.parse(x.info)})))});
 useEffect(()=>{api('/settings').then(x=>{const c={enabled:false,allowlist:[],ports:[80,443],...x['local-network']};setCfg(c);setPorts(c.ports.join(','))}).catch(e=>setError(errorText(e)));load().catch(e=>setError(errorText(e)))},[]);
 async function act(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function saveConfig(value=cfg){const c={...value,ports:ports.split(',').map(x=>Number(x.trim()))};await api('/settings/local-network','PUT',c);setCfg(c)}
 async function saveService(){await api('/local-network/services/'+(id||crypto.randomUUID()),'PUT',{...service,readPaths:paths.split('\n').map(s=>s.trim()).filter(Boolean)});setService(blank());setPaths('');setId('');await load()}
 async function stage(file:File){if(file.size>5_000_000)throw Error('Datei maximal 5 MB.');const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(Error('Datei nicht lesbar.'));r.readAsDataURL(file)});await api('/local-network/files','POST',{fileName:file.name,contentBase64:data});await load()}
 return <><section className="panel"><h2>Lokales Netzwerk – getrennt von Research</h2><p className="muted">Ausgeschaltet, bis du Server- und Dashboard-Allowlist freigibst. DNS-Namen benötigen zusätzlich passende IP-/CIDR-Einträge. Keine pauschalen Netzscans. Interne Antworten werden nicht als Webseite ausgeführt.</p>{error&&<p role="alert" className="error">{error}</p>}
 <label className="check"><input type="checkbox" checked={!!cfg.enabled} onChange={e=>setCfg({...cfg,enabled:e.target.checked})}/>Local Network aktivieren</label>
 <div className="row"><input aria-label="Netz oder Host" value={entry} onChange={e=>setEntry(e.target.value)} placeholder="192.168.178.0/24 oder nas.home"/><button disabled={busy} onClick={()=>{if(entry.trim()){setCfg({...cfg,allowlist:[...new Set([...cfg.allowlist,entry.trim()])]});setEntry('')}}}>Netz / Host hinzufügen</button></div>
 {cfg.allowlist.map((host:string)=><div className="row" key={host}><code>{host}</code><button onClick={()=>setCfg({...cfg,allowlist:cfg.allowlist.filter((x:string)=>x!==host)})}>Entfernen</button></div>)}
 <label>Erlaubte einzelne Ports<input value={ports} onChange={e=>setPorts(e.target.value)} placeholder="80,443,8123"/></label>
 <label className="check"><input type="checkbox" checked={!!cfg.probesEnabled} onChange={e=>setCfg({...cfg,probesEnabled:e.target.checked})}/>Gezielte Host-/Portprüfung erlauben</label>
 <label className="check"><input type="checkbox" checked={!!cfg.discoveryEnabled} onChange={e=>setCfg({...cfg,discoveryEnabled:e.target.checked})}/>Opt-in: registrierte Ziele alle 15 Minuten niedrigfrequent prüfen</label>
 <label className="check"><input type="checkbox" checked={!!cfg.allowModelContext} onChange={e=>setCfg({...cfg,allowModelContext:e.target.checked})}/>Im lokalen Auftrag Ergebnisse an meinen KI-Anbieter übertragen</label>
 <div className="row"><button className="primary" disabled={busy} onClick={()=>act(()=>saveConfig())}>Netzwerkregeln speichern</button><button disabled={busy} onClick={()=>act(async()=>{await saveConfig({...cfg,enabled:false})})}>Zugriff deaktivieren</button><button disabled={busy} onClick={()=>act(async()=>setPolicy(await api('/local-network/policy')))}>Servergrenzen prüfen</button></div>{policy&&<pre>{JSON.stringify(policy,null,2)}</pre>}</section>
 <section className="panel"><div className="sectionhead"><h2>Registrierte Dienste & Geräte</h2><button onClick={()=>act(load)}>Aktualisieren</button></div>{services.length===0&&<p className="muted">Keine Dienste registriert. Bekannte Endpunkte haben Vorrang vor Discovery.</p>}
 {services.map(s=><article className="record" key={s.id}><h3>{s.service.name}</h3><p>{s.service.host}:{s.service.port} · {s.service.type} · {s.service.permission}</p><small>ID: {s.id}<br/>Revision: {s.service.revision}</small><p className="muted">{s.service.enabled?'Aktiviert':'Deaktiviert'} · {s.status?.status||'Noch nicht geprüft'} · {s.status?.latencyMs??'–'} ms<br/>Letzter Erfolg: {s.status?.lastSuccess||'–'}</p><div className="row"><button onClick={()=>{setService(s.service);setId(s.id);setPaths(s.service.readPaths.join('\n'))}}>Bearbeiten</button><button disabled={busy} onClick={()=>act(async()=>{const r=await api('/tools/execute','POST',{name:'LocalNetwork.CheckPort',args:{serviceId:s.id,revision:s.service.revision}});setAnswer(JSON.stringify(r,null,2));await load()})}>Verbindung testen</button><button disabled={busy} onClick={()=>act(async()=>{await api('/local-network/services/'+s.id,'PUT',{...s.service,enabled:!s.service.enabled});await load()})}>{s.service.enabled?'Deaktivieren':'Aktivieren'}</button><button className="danger" onClick={()=>{if(confirm('Diesen Dienst entfernen? Der separate Secret-Eintrag bleibt erhalten.'))act(async()=>{await api('/local-network/services/'+s.id,'DELETE');await load()})}}>Entfernen</button></div></article>)}</section>
 <section className="panel"><h2>{id?'Dienst bearbeiten':'Dienst hinzufügen'}</h2><div className="fields">
 <label>Name<input value={service.name} onChange={e=>setService({...service,name:e.target.value})}/></label><label>Host<input value={service.host} onChange={e=>setService({...service,host:e.target.value})}/></label>
 <label>Protokoll<select value={service.protocol} onChange={e=>setService({...service,protocol:e.target.value})}><option>https</option><option>http</option></select></label><label>Port<input type="number" min={1} max={65535} value={service.port} onChange={e=>setService({...service,port:Number(e.target.value)})}/></label>
 <label>Diensttyp<input value={service.type} onChange={e=>setService({...service,type:e.target.value})} placeholder="Nextcloud / Immich / Home Assistant / NAS …"/></label><label>Berechtigung<select value={service.permission} onChange={e=>setService({...service,permission:e.target.value})}><option>Read</option><option>Write</option><option>Admin</option></select></label>
 <label>Secret-Referenz (optional)<input value={service.credentialRef} onChange={e=>setService({...service,credentialRef:e.target.value})}/></label></div>
 <label>Als nebenwirkungsfrei geprüfte Lesepfade, einer pro Zeile<textarea rows={3} value={paths} onChange={e=>setPaths(e.target.value)} placeholder="/api/status"/></label><small>Ein abschließender / erlaubt alle Unterpfade. / gibt alle GET-Pfade frei; nur nach Prüfung verwenden.</small>
 <label className="check"><input type="checkbox" checked={service.enabled} onChange={e=>setService({...service,enabled:e.target.checked})}/>Dienst aktiviert</label><label className="check"><input type="checkbox" checked={service.autoCheck} onChange={e=>setService({...service,autoCheck:e.target.checked})}/>Diesen registrierten Port periodisch prüfen (separates Opt-in erforderlich)</label><label className="check"><input type="checkbox" checked={service.allowHttpCredentials} onChange={e=>setService({...service,allowHttpCredentials:e.target.checked})}/>Credentials unverschlüsselt per HTTP senden (nur nach bewusster Abwägung)</label>
 <button className="primary" disabled={busy} onClick={()=>act(saveService)}>Dienst speichern</button></section>
 <section className="panel"><h2>Credentials im Secret Store</h2><p className="muted">Nie in Auftrag, Dienstpfad oder Memory eingeben. Werte werden nach Speichern nicht zurückgegeben.</p><div className="fields"><label>Referenz-ID<input value={secret.id} onChange={e=>setSecret({...secret,id:e.target.value})}/></label><label>Typ<select value={secret.type} onChange={e=>setSecret({...secret,type:e.target.value})}><option>Bearer</option><option>Basic</option><option>Header</option></select></label>{secret.type==='Basic'&&<label>Benutzername<input value={secret.username} onChange={e=>setSecret({...secret,username:e.target.value})}/></label>}{secret.type==='Header'&&<label>Header<select value={secret.header} onChange={e=>setSecret({...secret,header:e.target.value})}><option>X-Api-Key</option><option>Api-Key</option><option>X-Auth-Token</option></select></label>}<label>Passwort / Token<input type="password" autoComplete="new-password" value={secret.value} onChange={e=>setSecret({...secret,value:e.target.value})}/></label></div><div className="row"><button disabled={busy} onClick={()=>act(async()=>{await api('/local-network/credentials/'+secret.id,'PUT',secret);setSecret({...secret,value:''})})}>Secret speichern</button><button className="danger" disabled={busy} onClick={()=>{if(confirm('Secret mit dieser Referenz löschen? Betroffene Dienste verlieren den Zugriff.'))act(async()=>{await api('/local-network/credentials/'+secret.id,'DELETE');setSecret({...secret,value:''})})}}>Secret entfernen</button></div></section>
 <section className="panel"><h2>Lokaler Auftrag</h2><p className="muted">Separater Verlauf, ausschließlich lokale Tools. Keine Webrecherche. Benötigt die explizite Modellkontext-Freigabe oben.</p><textarea rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Prüfe den freigegebenen Statusdienst."/><button disabled={busy||!cfg.allowModelContext} onClick={()=>act(async()=>{const controller=new AbortController();abort.current=controller;try{const r=await api('/local-network/chat','POST',{message,conversation:conversation.current},controller.signal);setAnswer(r.answer);await load()}finally{abort.current=null}})}>Lokalen Auftrag starten</button><button disabled={!busy} onClick={()=>abort.current?.abort()}>Auftrag stoppen</button>{answer&&<pre>{answer}</pre>}</section>
 <ToolPanel prefix="LocalNetwork." onChange={()=>load().catch(e=>setError(errorText(e)))}/>
 <section className="panel"><h2>Dateiquarantäne</h2><p className="muted">Maximal 5 MB, zehn Dateien. Verschlüsselt gespeichert, eine Stunde abrufbar, nicht automatisch ausgeführt oder auf Viren geprüft. Upload an einen Dienst benötigt eine eigene Freigabe.</p><label>Datei bewusst bereitstellen<input type="file" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)act(()=>stage(file));e.target.value=''}}/></label>{files.map(f=><article className="record" key={f.id}><strong>{f.info.fileName}</strong><p>{f.info.bytes} Bytes · {f.info.origin}</p><small>Datei-ID: {f.id}</small><div className="row"><a href={'/api/v1/local-network/files/'+encodeURIComponent(f.id)} download>Bewusst herunterladen</a><button className="danger" onClick={()=>act(async()=>{await api('/local-network/files/'+f.id,'DELETE');await load()})}>Löschen</button></div></article>)}</section></>
}
