import {useEffect,useState} from 'react';
import {api,Doc,errorText} from './api';
import {DataPanel} from './Panels';

export function TaskBoard(){
 const[items,setItems]=useState<Doc[]>([]),[goals,setGoals]=useState<Doc[]>([]),[description,setDescription]=useState(''),[kind,setKind]=useState('tasks'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=()=>Promise.all([api<Doc[]>('/data/tasks'),api<Doc[]>('/data/goals')]).then(([t,g])=>{setItems(t);setGoals(g)}).catch(e=>setError(errorText(e)));
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api('/operator/'+kind,'POST',{description});setDescription('');await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <><section className="panel"><h2>Ziele statt Mikrobefehle</h2><p className="muted">JARVIS arbeitet im Hintergrund. Deine Freigaben, Telefonregeln und KI-Budgets gelten auch hier.</p><form onSubmit={submit}><select value={kind} onChange={e=>setKind(e.target.value)}><option value="tasks">Einzelaufgabe</option><option value="goals">Ziel mit geplanter Aufgabenfolge</option></select><textarea required minLength={3} maxLength={10000} rows={4} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Welches Ergebnis möchtest du erreichen?"/><button className="primary" disabled={busy}>Auftrag starten</button></form>{error&&<p className="error">{error}</p>}</section>
 {goals.map(g=><section className="panel compact" key={g.id}><h3>{g.data.title}</h3><span className="badge">Ziel · {g.data.status}</span>{g.data.error&&<p className="error">{g.data.error}</p>}</section>)}
 <section className="panel"><h2>Aufgaben</h2>{items.length===0&&<p className="muted">Noch keine Aufgaben.</p>}{items.map(t=><article className="record" key={t.id}><div className="sectionhead"><h3>{t.data.title}</h3><span className="badge">{t.data.status}</span></div><p className="muted">{t.data.description}</p>{t.data.result?.answer&&<p className="prose">{t.data.result.answer}</p>}{t.data.error&&<p className="error">{t.data.error}</p>}<div className="row">{['Queued','Running','NeedsApproval'].includes(t.data.status)&&<button onClick={()=>api('/operator/tasks/'+t.id+'/stop','POST',{}).then(load).catch(e=>setError(errorText(e)))}>Stoppen</button>}{['Waiting','Failed'].includes(t.data.status)&&<button onClick={()=>{if(confirm('Externe Aktionen geprüft? Bereits ausgeführte Schreibaktionen werden nicht automatisch wiederholt.'))api('/operator/tasks/'+t.id+'/resume','POST',{}).then(load).catch(e=>setError(errorText(e)))}}>Fortsetzen</button>}</div></article>)}</section></>
}

const categories=['Identity','Preferences','Relationships','Work','Projects','Devices','Vehicles','Travel','Finances','Important Dates','Habits','Personal Rules','Past Decisions','Goals','Other'];
export function PersonalMemoryPanel(){
 const[records,setRecords]=useState<any[]>([]),[candidates,setCandidates]=useState<any[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[editing,setEditing]=useState<any>(),[history,setHistory]=useState<any[]>();
 const load=()=>api<any[]>('/memory/personal').then(setRecords).catch(e=>setError(errorText(e)));
 useEffect(()=>{load()},[]);
 async function save(entry:any){try{const id=entry.id||entry.candidateId||crypto.randomUUID();await api('/memory/personal/'+id,'PUT',{...entry,confidence:1,status:'accepted'});setEditing(null);setCandidates(c=>c.filter(x=>x.candidateId!==entry.candidateId));await load()}catch(e){setError(errorText(e))}}
 async function importFile(file:File){if(file.size>5_000_000){setError('Import maximal 5 MB.');return}try{setCandidates(await api('/memory/import/preview','POST',{text:await file.text(),format:file.name.endsWith('.json')?'json':'markdown'}))}catch(e){setError(errorText(e))}}
 return <><section className="panel"><h2>Persönliches Gedächtnis</h2><p className="muted">Verschlüsselt gespeichert, mit Quelle und Historie. Sensible Fakten werden nicht automatisch an KI-Modelle gesendet. Passwörter gehören in den Secret Store.</p><div className="row"><input aria-label="Memory durchsuchen" placeholder="Suchen …" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={()=>setEditing({category:'Other',fact:'',source:'User stated',sensitive:true})}>Neue Erinnerung</button></div><label>ChatGPT-Export (conversations.json), JSON oder Markdown importieren<input type="file" accept=".json,.md,.txt" onChange={e=>{const f=e.target.files?.[0];if(f)importFile(f);e.target.value=''}}/></label><small>Importe bleiben Kandidaten. Kein automatischer Cloudaufruf und kein Zugriff auf internes ChatGPT-Memory.</small>{error&&<p className="error">{error}</p>}</section>
 {editing&&<section className="panel"><h3>Erinnerung prüfen</h3><label>Kategorie<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Fakt<textarea rows={5} value={editing.fact} onChange={e=>setEditing({...editing,fact:e.target.value})}/></label><label>Quelle<input value={editing.source} onChange={e=>setEditing({...editing,source:e.target.value})}/></label><label className="check"><input type="checkbox" checked={editing.sensitive} onChange={e=>setEditing({...editing,sensitive:e.target.checked})}/>Sensibel – separate Lesefreigabe erforderlich</label><div className="row"><button className="primary" onClick={()=>save(editing)}>Übernehmen</button><button onClick={()=>setEditing(null)}>Abbrechen</button></div></section>}
 {candidates.length>0&&<section className="panel"><h3>Import-Vorschau · {candidates.length} Kandidaten</h3><p className="muted">Benutzeraussagen aus dem Export, noch keine verifizierten Fakten. Widersprüche bitte prüfen.</p>{candidates.map(c=><article className="record" key={c.candidateId}><p>{c.fact}</p>{c.duplicate&&<span className="badge">Bereits vorhanden</span>}<div className="row"><button onClick={()=>setEditing(c)}>Prüfen / Bearbeiten</button><button onClick={()=>setCandidates(x=>x.filter(v=>v.candidateId!==c.candidateId))}>Ablehnen</button></div></article>)}</section>}
 <section className="panel">{records.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())).map(r=><article className="record" key={r.id}><span className="badge">{r.category} · {r.sensitive?'Sensibel':'Kontext freigegeben'}</span><p>{r.fact}</p><small>Quelle: {r.source} · {new Date(r.updated_at).toLocaleString()}</small><div className="row"><button onClick={()=>setEditing(r)}>Bearbeiten</button><button onClick={()=>save({...r,pinned:!r.pinned})}>{r.pinned?'Lösen':'Anheften'}</button><button onClick={()=>api<any[]>('/memory/personal/'+r.id+'/history').then(setHistory).catch(e=>setError(errorText(e)))}>Historie</button><button className="danger" onClick={()=>{if(confirm('Erinnerung und Historie löschen?'))api('/memory/personal/'+r.id,'DELETE').then(load).catch(e=>setError(errorText(e)))}}>Löschen</button></div></article>)}</section>{history&&<section className="panel"><h3>Vorherige Versionen</h3>{history.length===0?<p>Keine früheren Versionen.</p>:history.map(h=><article className="record" key={h.id}><small>{h.at}</small><p>{h.data.fact}</p></article>)}<button onClick={()=>setHistory(undefined)}>Schließen</button></section>}</>
}

export function ModelDashboard(){
 const[usage,setUsage]=useState<any[]>([]),[error,setError]=useState('');
 const load=()=>api<any[]>('/ai/usage').then(setUsage).catch(e=>setError(errorText(e)));
 useEffect(()=>{load()},[]);
 const total=(days:number)=>usage.filter(u=>Date.now()-Date.parse(u.day)<days*86400000).reduce((n,u)=>n+Number(u.estimated_cost),0);
 return <><section className="panel"><h2>Modelle & Verbrauch</h2><p className="muted">Standard: Best Value. Nur validierte Registry-Modelle werden automatisch ausgewählt. Preise in USD pro Million Tokens; unbekannte Preise sind keine Nullkosten.</p><div className="metrics">{[[1,'24 Stunden'],[7,'7 Tage'],[31,'31 Tage']].map(([d,label])=><div className="metric" key={d}><small>{label}</small><strong>${total(Number(d)).toFixed(3)}</strong></div>)}</div>{usage.some(u=>!u.price_known)&&<p className="notice">Unbekannte Modellpreise: Die Gesamtsumme ist unvollständig. Realtime-Audio ist separat beim Anbieter zu prüfen.</p>}<div className="row"><button onClick={load}>Verbrauch aktualisieren</button><button onClick={()=>api('/ai/models/discover','POST',{}).then(()=>setError('Neue Modelle als AVAILABLE_NOT_VALIDATED gespeichert. Registry aktualisieren.')).catch(e=>setError(errorText(e)))}>Verfügbare Modelle entdecken</button></div>{error&&<p role="status">{error}</p>}<div className="tablewrap"><table><thead><tr><th>Modell</th><th>Typ</th><th>Input / Cache / Output</th><th>USD (geschätzt)</th></tr></thead><tbody>{usage.map((u,i)=><tr key={i}><td>{u.model}</td><td>{u.task_type}</td><td>{u.input_tokens} / {u.cached_tokens} / {u.output_tokens}</td><td>{u.price_known?Number(u.estimated_cost).toFixed(5):'unbekannt'}</td></tr>)}</tbody></table></div></section><DataPanel kind="ai-models" title="Model Registry · Expert Settings"/></>
}

export function SipStatus(){
 const[state,setState]=useState<any>(),[error,setError]=useState('');
 const load=()=>api('/phone/sip/status').then(s=>{setState(s);setError('')}).catch(e=>setError(errorText(e)));
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 return <section className="panel"><div className="sectionhead"><h2>SIP-Telefonie</h2><button onClick={load}>Status prüfen</button></div><p className="muted">Audioaufzeichnung: AUS. Textprotokolle sind für aktivierte KI-Gespräche vorgesehen.</p>{error&&<p className="notice">{error}</p>}{state?.accounts?.map((a:any)=><article className="record" key={a.id}><strong>{a.name}</strong><span className="badge">{a.registered?'Registered':a.state}</span><small>Aktive Gespräche: {a.activeCalls} · Letzter Registrierungsversuch: {a.lastAttempt}</small></article>)}</section>
}
