import {useEffect,useState} from 'react';
import {api,Doc,Tool,errorText} from './api';
export function ToolPanel({prefix='',onChange}:{prefix?:string;onChange?:()=>void}){
 const[tools,setTools]=useState<Tool[]>([]),[selected,setSelected]=useState(''),[args,setArgs]=useState<Record<string,unknown>>({}),[result,setResult]=useState<any>(),[busy,setBusy]=useState(false);
 useEffect(()=>{api<Tool[]>('/tools').then(t=>{const filtered=t.filter(x=>!prefix||x.name.startsWith(prefix));setTools(filtered);setSelected(filtered[0]?.name||'');setArgs({})}).catch(e=>setResult({error:errorText(e)}))},[prefix]);
 const tool=tools.find(t=>t.name===selected);
 async function execute(e:React.FormEvent){e.preventDefault();setBusy(true);try{setResult(await api('/tools/execute','POST',{name:selected,args}));onChange?.()}catch(e){setResult({error:errorText(e)})}finally{setBusy(false)}}
 return <section className="panel"><h2>Aktion ausführen</h2><form onSubmit={execute}><label>Fähigkeit<select value={selected} onChange={e=>{setSelected(e.target.value);setArgs({});setResult(null)}}>{tools.map(t=><option key={t.name}>{t.name}</option>)}</select></label><p className="muted">{tool?.description}</p><div className="fields">{Object.entries(tool?.fields||{}).map(([key,f])=><label key={key}>{f.description}{f.choices?<select required={f.required} value={String(args[key]??'')} onChange={e=>setArgs({...args,[key]:e.target.value})}><option value="">Bitte wählen</option>{f.choices.map(c=><option key={c}>{c}</option>)}</select>:f.type==='boolean'?<input type="checkbox" checked={!!args[key]} onChange={e=>setArgs({...args,[key]:e.target.checked})}/>:<input required={f.required} type={f.type==='integer'||f.type==='number'?'number':'text'} value={String(args[key]??'')} onChange={e=>setArgs({...args,[key]:f.type==='integer'||f.type==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div><button className="primary" disabled={busy||!tool}>{busy?'Wird ausgeführt …':tool?.risk===0?'Ausführen':'Aktion anfragen'}</button></form>
 {result?.approvalId&&<p className="notice">Diese Aktion wartet unter „Freigaben“ auf deine Bestätigung.</p>}
 {result?.data?.image?<img className="screenshot" src={result.data.image} alt="Aktueller Browser-Screenshot"/>:result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section>
}
export function DataPanel({kind,title}:{kind:string;title:string}){
 const[data,setData]=useState<Doc[]>([]),[error,setError]=useState(''),[edit,setEdit]=useState(''),[id,setId]=useState(''),[contact,setContact]=useState({name:'',email:'',phone:'',company:'',relationship:'',notes:'',tags:''});
 const load=()=>api<Doc[]>('/data/'+kind).then(setData).catch(e=>setError(errorText(e)));
 useEffect(()=>{load()},[kind]);
 const writable=['contacts','automations','tasks','ai-models','event-rules'].includes(kind);
 async function save(){try{const body=kind==='contacts'?contact:JSON.parse(edit);await api('/data/'+kind+'/'+(id||crypto.randomUUID()),'PUT',body);setEdit('');setId('');await load()}catch(e){setError(errorText(e))}}
 return <><section className="panel"><div className="sectionhead"><h2>{title}</h2><div className="row">{kind==="research"&&<button className="danger" onClick={async()=>{if(!confirm("Gesamten Rechercheverlauf löschen?"))return;try{await api("/data/research/all","DELETE");await load()}catch(e){setError(errorText(e))}}}>Verlauf löschen</button>}<button onClick={()=>load()}>Aktualisieren</button></div></div>{error&&<p className="error">{error}</p>}
 {data.length===0?<div className="empty">Hier gibt es noch keine Einträge.</div>:data.map(doc=><article className="record" key={doc.id}><div className="sectionhead"><strong>{doc.data.name||doc.data.title||doc.data.question||doc.data.number||doc.id.slice(0,12)}</strong><div className="row">{writable&&<button onClick={()=>{setId(doc.id);setEdit(JSON.stringify(doc.data,null,2));if(kind==='contacts')setContact(doc.data as typeof contact)}}>Bearbeiten</button>}<button className="danger" onClick={async()=>{if(!confirm('Diesen Eintrag löschen?'))return;try{await api('/data/'+kind+'/'+doc.id,'DELETE');load()}catch(e){setError(errorText(e))}}}>Löschen</button></div></div><p className="prose">{doc.data.summary}</p>{!doc.data.summary&&<pre>{JSON.stringify(doc.data,null,2)}</pre>}{Array.isArray(doc.data.sources)&&<div className="sources">{doc.data.sources.filter((source:any)=>/^https?:\/\//.test(source.url)).map((source:any)=><a key={source.number} href={source.url} target="_blank" rel="noreferrer">[{source.number}] {source.title}</a>)}</div>}<small>{new Date(doc.updatedAt).toLocaleString()}</small></article>)}</section>
 {writable&&<section className="panel"><h2>{id?'Eintrag bearbeiten':'Neuer Eintrag'}</h2>{kind==='contacts'?<div className="fields">{Object.entries(contact).map(([key,value])=><label key={key}>{({name:'Name',email:'E-Mail',phone:'Telefon',company:'Firma',relationship:'Beziehung',notes:'Notizen',tags:'Tags'} as Record<string,string>)[key]}<input value={value} onChange={e=>setContact({...contact,[key]:e.target.value})}/></label>)}</div>:<><p className="muted">{kind==='ai-models'?'Modell als JSON; Preise pro Million Tokens und Fähigkeiten vor Aktivierung prüfen. Vorlage: docs/OPERATOR.md.':kind==='event-rules'?'Ereignisregel mit event, enabled, urgency, impact, relevance, message und optional allowCall.':kind==='automations'?'Zeitregel: trigger=time, nextRun als ISO-Zeit, intervalMinutes (0 = einmalig), tool und args. Aktionen nutzen dieselben Freigaben wie Chat.':'Aufgabe als JSON mit title, description und status.'}</p><textarea rows={12} placeholder={kind==='ai-models'?'{"model_name":"DEIN_MODELL","enabled":false,"validated":false,"capability_level":0,"context_window":32000,"supports_tools":true,"input_cost":null,"output_cost":null}':kind==='event-rules'?'{"event":"low-battery","enabled":false,"urgency":20,"impact":30,"relevance":40,"message":"Der Akku ist niedrig.","allowCall":false}':kind==='automations'?'{"name":"Erinnerung","enabled":true,"trigger":"time","nextRun":"2026-09-26T07:00:00+02:00","intervalMinutes":0,"tool":"Memory.Search","args":{"query":"Projekt"}}':'{"title":"Meine Aufgabe","status":"open"}'} value={edit} onChange={e=>setEdit(e.target.value)}/></>}<button className="primary" onClick={save}>Speichern</button></section>}</>
}
export function Permissions(){
 const[tools,setTools]=useState<Tool[]>([]),[saved,setSaved]=useState<Doc[]>([]),[status,setStatus]=useState('');
 useEffect(()=>{Promise.all([api<Tool[]>('/tools'),api<Doc[]>('/permissions')]).then(([t,p])=>{setTools(t);setSaved(p)}).catch(e=>setStatus(errorText(e)))},[]);
 async function update(tool:Tool,permission:string,tenMinutes=false){try{await api('/permissions/'+encodeURIComponent(tool.name),'PUT',{permission,tenMinutes});setSaved(await api('/permissions'));setStatus('Berechtigung gespeichert.')}catch(e){setStatus(errorText(e))}}
 return <section className="panel"><h2>Du entscheidest, was JARVIS darf.</h2><p className="muted">Finanzielle oder nicht eindeutig begrenzbare Browseraktionen bleiben bestätigungspflichtig.</p><p role="status">{status}</p><div className="tablewrap"><table><thead><tr><th>Fähigkeit</th><th>Risikostufe</th><th>Berechtigung</th><th>Zeitfreigabe</th></tr></thead><tbody>{tools.map(t=><tr key={t.name}><td><strong>{t.name}</strong><small>{t.description}</small></td><td>{['SAFE','CONFIRM','ALWAYS CONFIRM'][t.risk]}</td><td><select aria-label={'Berechtigung '+t.name} value={saved.find(p=>p.id===t.name&&(!p.data.expiresAt||Date.parse(p.data.expiresAt)>Date.now()))?.data.permission||''} onChange={e=>update(t,e.target.value)}><option value="" disabled>Standard-Autonomiepolicy</option><option value="Allow" disabled={t.risk===2}>Immer erlauben</option><option value="Auto" disabled={t.risk===2}>AUTO</option><option value="Notify" disabled={t.risk===2}>NOTIFY (Aktivitätsfeed)</option><option value="Ask">ASK</option><option value="AlwaysConfirm">ALWAYS_CONFIRM</option><option value="Deny">Sperren</option></select></td><td><button disabled={t.risk===2} onClick={()=>update(t,'Allow',true)}>10 Minuten</button></td></tr>)}</tbody></table></div></section>
}
export function Approvals({onChange}:{onChange:()=>void}){
 const[items,setItems]=useState<any[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState('');
 const load=()=>api<any[]>('/approvals').then(setItems).catch(e=>setStatus(errorText(e)));
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[]);
 async function decide(id:string,approve:boolean){setBusy(id);try{const r=await api('/approvals/'+id,'POST',{approve});setStatus(JSON.stringify(r));await load();onChange()}catch(e){setStatus(errorText(e))}finally{setBusy('')}}
 return <section className="panel"><h2>Ausstehende Freigaben</h2><p className="muted">Prüfe Ziel und Inhalt. Die Bestätigung gilt nur für genau diese Aktion und verfällt nach 10 Minuten.</p>{status&&<pre role="status">{status}</pre>}{items.length===0&&<div className="empty">Zurzeit braucht keine Aktion deine Freigabe.</div>}{items.map(a=><article className="approval" key={a.id}><h3>{a.tool}</h3>{a.local_host&&<p>Ziel: {a.local_host}:{a.local_port} {JSON.parse(a.args).revision!==a.local_revision&&<strong>– Konfiguration geändert; diese Freigabe ist nicht mehr ausführbar.</strong>}</p>}<pre>{JSON.stringify(JSON.parse(a.args),null,2)}</pre><small>Gültig bis {new Date(a.expires_at).toLocaleTimeString()}</small><div className="row"><button disabled={!!busy} onClick={()=>decide(a.id,false)}>Ablehnen</button><button className="primary" disabled={!!busy} onClick={()=>decide(a.id,true)}>Diese Aktion bestätigen</button></div></article>)}</section>
}
