import {useEffect,useState} from 'react';
import {api,errorText} from './api';
export const sections:Record<string,{label:string;fields:[string,string,string][]}>={
 phone:{label:'Telefonie',fields:[['provider','Provider (sip oder twilio; Standard sip)','text'],['audioEnabled','Telefon-Audio an OpenAI übertragen und Textprotokoll speichern','checkbox'],['userNumber','Meine Rufnummer (+49…)','tel'],['allowedCountries','Erlaubte Ländervorwahlen, z. B. ["+49"]','json'],['blockedPrefixes','Zusätzliche gesperrte Vorwahlen','json'],['allowedNumbers','Optionale Rufnummern-Allowlist','json'],['maxCallsPerHour','Anrufversuche pro Stunde','number'],['maxIncomingPerHour','Eingehende Anrufe pro Stunde','number'],['maxCallDuration','Maximale Dauer in Sekunden','number']]},
 sip:{label:'SIP-Konten',fields:[['enabled','SIP aktivieren','checkbox'],['defaultAccount','Standardkonto-ID','text'],['accounts','SIP-Konten ohne Passwörter als JSON (Vorlage in docs/SIP.md)','json'],['accountSecretId','Konto-ID für das folgende Passwort','text'],['accountPassword','SIP-Passwort (leer = beibehalten)','password'],['routingRules','Routing-Regeln als JSON','json'],['allowFallback','Fallback vor dem Wählen erlauben','checkbox'],['fallbackAccount','Fallback-Konto-ID','text']]},
 nextcloud:{label:'Nextcloud',fields:[['enabled','Verbinden','checkbox'],['url','Nextcloud Basis-URL','url'],['username','Benutzername','text'],['password','App-Passwort (leer = beibehalten)','password'],['root','Freigegebener Unterordner (optional)','text'],['writable','Schreibzugriff','checkbox'],['indexEnabled','Inhalte für semantischen Index an Embedding-Anbieter übertragen','checkbox']]},
 immich:{label:'Immich',fields:[['enabled','Verbinden','checkbox'],['url','Immich Basis-URL','url'],['apiKey','API-Key','password'],['allowVision','Freigegebene Vorschauen an Vision-Modell übertragen','checkbox']]},
 autonomy:{label:'Autonomie',fields:[['level','Level 0–3 (Standard 3; irreversible Aktionen bleiben geschützt)','number']]},
 budget:{label:'KI-Budget',fields:[['mode','economy / balanced / best_value / maximum_quality / custom','text'],['dailySoft','Tägliches Soft-Limit (USD)','number'],['dailyHard','Tägliches Hard-Limit (USD)','number'],['monthlySoft','Monatliches Soft-Limit (USD)','number'],['monthlyHard','Monatliches Hard-Limit (USD)','number']]},
 events:{label:'Ereignisse',fields:[['enabled','Ereignisbewertung aktivieren','checkbox'],['quietStart','Ruhezeit beginnt (0–23)','number'],['quietEnd','Ruhezeit endet (0–23)','number'],['criticalCalls','Kritische Anrufe anfordern (Policy bleibt wirksam)','checkbox']]},
 ai:{label:'KI & Modelle',fields:[['enabled','Aktiviert','checkbox'],['protocol','Protokoll (responses oder chat)','text'],['baseUrl','API-Basis-URL','url'],['apiKey','API-Key (leer = beibehalten)','password'],['model','Aufgabenmodell','text'],['visionModel','Vision-Modell','text'],['realtimeModel','Realtime-Modell','text'],['transcriptionModel','Telefon-Transkriptionsmodell','text'],['embeddingModel','Embedding-Modell (optional, für Memory.Index)','text']]},
 internet:{label:'Internet & Research',fields:[['enabled','Websuche aktiv','checkbox'],['provider','Provider (brave oder searxng)','text'],['apiKey','Brave API-Key','password'],['searxUrl','SearXNG URL','url'],['browser','Browser aktiv','checkbox'],['automation','Browser-Automation aktiv','checkbox'],['deepResearch','Deep Research aktiv','checkbox'],['downloads','Downloads aktiv','checkbox'],['pdf','PDF-Lesen aktiv','checkbox'],['maxPages','Maximale Seiten','number'],['maxDurationSeconds','Maximale Dauer (Sekunden)','number'],['maxDownloadMb','Downloadlimit (MB)','number']]},
 google:{label:'Google Calendar & Gmail',fields:[['enabled','Verbindung aktiv','checkbox'],['clientId','OAuth Client-ID','text'],['clientSecret','OAuth Client-Secret','password']]},
 microsoft:{label:'Microsoft 365',fields:[['enabled','Verbindung aktiv','checkbox'],['clientId','Application Client-ID','text'],['clientSecret','Client-Secret','password']]},
 twilio:{label:'Twilio Telefonie',fields:[['enabled','Telefonie aktiv','checkbox'],['realtime','ConversationRelay Streaming (Twilio-Freischaltung erforderlich)','checkbox'],['accountSid','Account SID','text'],['authToken','Auth Token','password'],['number','Twilio Nummer (+49…)','tel'],['callerId','Verifizierte Caller-ID','tel']]},
 obsidian:{label:'Obsidian',fields:[['enabled','Vault verwenden','checkbox'],['writable','Schreibzugriff erlauben','checkbox']]},
 voice:{label:'Live Voice',fields:[['enabled','Audio an konfigurierten Anbieter übertragen','checkbox']]}
};
export function Fields({section,value,onChange}:{section:string;value:Record<string,any>;onChange:(v:Record<string,any>)=>void}){
 return <div className="fields">{sections[section].fields.map(([key,label,type])=><label key={key} className={type==='checkbox'?'check':''}>{type==='json'?<>{label}<JsonField value={value[key]} onChange={v=>onChange({...value,[key]:v})}/></>:type==='checkbox'?<><input type="checkbox" checked={!!value[key]} onChange={e=>onChange({...value,[key]:e.target.checked})}/>{label}</>:<>{label}<input type={type} autoComplete={type==='password'?'new-password':'off'} value={value[key]??''} onChange={e=>onChange({...value,[key]:type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value})}/></>}</label>)}</div>
}
export default function Settings({initial='ai'}:{initial?:string}){
 const [all,setAll]=useState<Record<string,any>>({}),[section,setSection]=useState(initial),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[mfa,setMfa]=useState<any>(),[code,setCode]=useState('');
 useEffect(()=>{api('/settings').then(setAll).catch(e=>setMessage(errorText(e)))},[]);
 async function act(action:()=>Promise<unknown>){setBusy(true);try{await action();setMessage('Erfolgreich.')}catch(e){setMessage(errorText(e))}finally{setBusy(false)}}
 return <><div className="tabs">{Object.entries(sections).map(([k,s])=><button className={section===k?'selected':''} key={k} onClick={()=>setSection(k)}>{s.label}</button>)}</div>
 <section className="panel"><h2>{sections[section].label}</h2><Fields section={section} value={all[section]||{}} onChange={v=>setAll({...all,[section]:v})}/>
 {section==='obsidian'&&<p className="muted">Der Vault-Pfad wird beim Start als OBSIDIAN_HOST_PATH gemountet. Dateien bleiben auf deinem Server.</p>}
 {['google','microsoft'].includes(section)&&<p className="muted">OAuth-Weiterleitung: {location.origin}/api/v1/oauth/{section}/callback</p>}
 <div className="row"><button disabled={busy} className="primary" onClick={()=>act(async()=>{if(document.querySelector('textarea[aria-invalid="true"]'))throw new Error('Bitte zuerst ungültiges JSON korrigieren.');await api('/settings/'+section,'PUT',all[section]||{});const cleaned={...all[section]};['apiKey','clientSecret','authToken','password','accountPassword','accountSecretId'].forEach(k=>delete cleaned[k]);if(section==='sip'&&Array.isArray(cleaned.accounts))cleaned.accounts=cleaned.accounts.map((a:any)=>{const b={...a};delete b.password;return b});setAll({...all,[section]:cleaned})})}>Speichern</button>
 {['ai','internet','google','microsoft','twilio','sip','nextcloud','immich'].includes(section)&&<button disabled={busy} onClick={()=>act(()=>api('/settings/'+section+'/test','POST',{}))}>Verbindung testen</button>}
 {['google','microsoft'].includes(section)&&<button disabled={busy} onClick={()=>act(async()=>{const r=await api('/oauth/'+section+'/start','POST',{});location.assign(r.url)})}>Konto verbinden</button>}</div><p role="status">{message}</p></section>
 <section className="panel"><h2>Zwei-Faktor-Anmeldung</h2><p className="muted">TOTP-Schlüssel in einer Authenticator-App speichern. Sichere zusätzlich dein verschlüsseltes Backup und den Master-Key.</p>
 {!mfa?<button onClick={()=>act(async()=>setMfa(await api('/auth/mfa/enroll','POST',{})))}>MFA einrichten</button>:<><code className="secret">{mfa.secret}</code><label>Bestätigungscode<input value={code} inputMode="numeric" onChange={e=>setCode(e.target.value)}/></label><button onClick={()=>act(async()=>{await api('/auth/mfa/confirm','POST',{code});setMfa(null)})}>MFA aktivieren</button></>}</section></>
}
function JsonField({value,onChange}:{value:any;onChange:(value:any)=>void}){
 const[text,setText]=useState(JSON.stringify(value??[],null,2)),[invalid,setInvalid]=useState(false);
 useEffect(()=>{setText(JSON.stringify(value??[],null,2));setInvalid(false)},[value]);
 return <><textarea rows={6} value={text} aria-invalid={invalid} onChange={e=>{setText(e.target.value);try{onChange(JSON.parse(e.target.value));setInvalid(false)}catch{setInvalid(true)}}}/>{invalid&&<small className="danger">JSON ungültig. Der letzte gültige Wert bleibt unverändert.</small>}</>
}
